{% set name = "apache-airflow-providers-trino" %}
{% set version = "5.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_trino-{{ version }}.tar.gz
  sha256: ef185c2fdd0d87c7ea4893b5c1e77d1d40dcc155a1b382af146b6fe043865428

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.8.0
    # the more restrictive constraint to stay noarch: python
    - pandas >=2.1.2,<2.2
    - trino-python-client >=0.318.0

test:
  imports:
    - airflow.providers.trino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-trino for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/trino/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-trino/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
