{% set name = "apache-airflow-providers-trino" %}
{% set version = "6.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_trino-{{ version }}.tar.gz
  sha256: 0732b53cfd873669d47ed53f6dfb1cd3fadbe9e5c34259c80019fbf993db7195

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-sql >=1.20.0
    # the more restrictive constraint to stay noarch: python
    - pandas >=2.2.3
    - trino-python-client >=0.319.0

test:
  imports:
    - airflow.providers.trino
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-trino for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/trino/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-trino/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
